@startuml Phonological
start

:The simulator choose words from the presented text;
:Combine words together;
:The simulator choose another words from the presented text;
:Create unfamilier words;
:Apply changes to the text;
stop
@enduml