@startuml surface
start

:The simulator choose words from the presented text;
:Warp letters within a word;
:The simulator choose another words from the presented text;
:Change font color;
:Apply changes to text;

stop
@enduml
