@startuml surface
start

:The simulator choose words from the presented text;
:Change font style;
:The simulator choose sentences from the presented text;
:Apply blur effect to the sentences;
:Apply changes to the text;

stop
@enduml
