@startuml surface
start

: The extension chooses sentences from the presented text;
: Change font style;
: The extension chooses other sentences from the presented text;
while (Is the selected sentence the same?) is (yes)
    : Choose another sentence from the presented text;
endwhile (no)
: Remove vowels within the words;
: Apply changes to the text;

stop
@enduml
