@startuml Visual
start

:The simulator choose some sentences from the presented text;
:Make sentences moves left and right;
:The simulator choose words from the presented text; 
:Transform the presented letters in a word into their mirror;
:The simulator choose another words from the presented text;
:Rearrange letters within a word;
:Apply changes to text;
stop
@enduml